spring:
  application:
    name: tienda-app
  profiles:
    default: dev
  threads:
    virtual:
      enabled: true
  cache:
    type: caffeine
    cache-names: activeDiscounts
    caffeine:
      spec: expireAfterWrite=10m,maximumSize=100
  jpa:
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max.block.ms: 5000
        request.timeout.ms: 5000
        delivery.timeout.ms: 10000

    consumer:
      group-id: order-processing-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.lucho.tienda.messaging
        spring.json.value.default.type: com.lucho.tienda.messaging.OrderProcessingMessage

jwt:
  expiration: 3600000

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    org.hibernate.SQL: ERROR
  file:
    name: logs/application.log

cart:
  processing:
    sleep-ms: 0
    retry:
      max-attempts: 10
      backoff-delay: 150
      multiplier: 2.0

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: when_authorized
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
